[versions]
agp = "9.0.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
pytorch_android_lite = "2.1.0"
pytorch_android_torchvision_lite = "2.1.0"
appUpdate = "2.1.0"
faceDetection = "16.1.7"
glide = "5.0.5"
loggingInterceptor = "5.3.2"
places = "5.1.1"
circleimageview = "3.1.0"
recyclerview = "1.4.0"
lifecycleExtensions = "2.2.0"
cardview = "1.0.0"
browser = "1.10.0-alpha02"
playServicesAuthApiPhone = "18.3.0"
playServicesAuth = "21.5.0"
annotations = "26.0.2-1"
multidex = "2.0.1"
playServicesLocation = "21.3.0"
playServicesMaps = "19.2.0"
volley = "1.2.1"
kotlinxCoroutinesAndroid = "1.10.2"
okhttp = "5.3.2"
gson = "2.13.2"
runner = "1.7.0"
shimmer = "0.5.0"
converterGson = "3.0.0"
firebaseBom = "34.7.0"
swiperefreshlayout = "1.2.0-alpha01"

cameraCore = "1.6.0-alpha02"
cameraCamera2 = "1.6.0-alpha02"
cameraLifecycle = "1.6.0-alpha02"
cameraView = "1.6.0-alpha02"
firebaseMessaging = "25.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
pytorch_android_lite = { group = "org.pytorch", name = "pytorch_android_lite", version.ref = "pytorch_android_lite" }
pytorch_android_torchvision_lite = { group = "org.pytorch", name = "pytorch_android_torchvision_lite", version.ref = "pytorch_android_torchvision_lite" }
app-update = { group = "com.google.android.play", name = "app-update", version.ref = "appUpdate" }
face-detection = { group = "com.google.mlkit", name = "face-detection", version.ref = "faceDetection" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycleExtensions" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
play-services-auth-api-phone = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "playServicesAuthApiPhone" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

